#!/bin/sh

git checkout nadiaexp_smp

module load intel/mkl/64/11.2/2015.3.187

#BSUB -a openmp
#BSUB -q fat-short
#BSUB -W 00:05
#BSUB -n 34
#BSUB -o out.optim.%J
#BSUB -R span[hosts=1]

mpirun.lsf Rscript --slave -f "optim_run_script_paral.R"
